# permissions for end users to view slurms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: slurm-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: slurm-operator
    app.kubernetes.io/part-of: slurm-operator
    app.kubernetes.io/managed-by: kustomize
  name: slurm-viewer-role
rules:
- apiGroups:
  - flux-framework.org
  resources:
  - slurms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flux-framework.org
  resources:
  - slurms/status
  verbs:
  - get
