name: build slurm-containers

on:
  pull_request: []
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    env:
      container: ghcr.io/converged-computing/slurm
    runs-on: ubuntu-latest
    name: make and build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Container
      run: docker build -f docker/Dockerfile -t ${{ env.container }} ./docker

    - name: Deploy Container
      if: (github.event_name != 'pull_request')
      run: docker push ${{ env.container }}
